### ISSUE TITLE
Subtitles ?

### ISSUE THREAD

**Issue by nightwolfz** [dreamvids/webm-info#1]
I've been trying to extract subtitles using go-mkv all day long with only partial success.

I managed to get the text out but I cannot figure out how to get the start/duration.

Could you help or give me a hint in the right direction?

Thanks!

**Comment by quadrifoglio** [comment]
Hi Ryan !

You did the hard part figuring out how to get the text out.

The duration of a subtitle block is encoded in a BlockDuration element (0x9B) as an unsigned int.
Just like any other kind of block, the starting point (timecode) is stored in the Block/SimpleBlock header, right after the track number.
However that timecode is relative to the parent cluster's timecode, so you will need that to calculate the real value of the starting point.

You can look at [https://www.matroska.org/technical/specs/index.html#simpleblock_structure](url) to see the details.

Good luck !

**Comment by nightwolfz** [comment]
That was exactly what I needed! I managed to get everything now :)

Merci fieu!
